variable project {
  default = "erento-beta"
}

variable region {
  default = "europe-west1"
}

variable zones {
  default = ["b", "c", "d"]
}

variable server_prefix {
  default = "glusterfs-server"
}

variable network {
  description = "Network Name on Google Cloud to place the gluster cluster in - this needs to exist"
  default     = "default"
}

variable subnetwork {
  description = "Subnetwork Name on Google Cloud to place the gluster cluster in - this will be created"
  default     = "default"
}

variable volume_names {
  description = "Names of the volumes that module creates"
  type        = "list"
}

variable subnet_mask {
  description = "Network CIDR to place the gluster cluster in"
  default     = "10.0.0.0/24"
}

variable ip_offset {
  description = "We are using last bit of the 'subnet_mask' i.e. 10.0.0.254, 10.0.0.253 - increase if you those IPs are alredy taken"
  default     = 3
}

variable replicas_number {
  description = "How many replicas of each file should gluster keep"
  default     = 3
}

variable disk_prefix {
  default = "glusterfs-brick"
}

variable data_disk_size {
  default     = "100"
  description = "GlusterFS data disk size in GB"
}

variable machine_type {
  default = "n1-standard-1"
}

variable boot_disk_size {
  default     = "10"
  description = "VMs disk boot size in GB"
}

variable cluster_size {
  default = 3
}

variable disk_type {
  default = "pd-ssd"
}

variable image {
  default = "ubuntu-1604-xenial-v20180522"
}

variable tags {
  type    = "list"
  default = ["gluster"]
}

variable allowed_source_tags {
  description = "Source tags on Google Cloud that will have access to gluster"
  type        = "list"
  default     = ["gluster"]
}

variable kubernetes_endpoint_name {
  default = "glusterfs-cluster"
}

variable disk_snapshot {
  default = ""
}

variable kubernetes_endpoint_file_path {
  default     = "glusterfs-endpoints.json"
  description = "Path to Kubernetes endpoint file generated by terraform"
}
