apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sample
  name: sample-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: sample-app
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /mnt/glusterfs
          name: glusterfsvol
      volumes:
      - name: glusterfsvol
        glusterfs:
          endpoints: glusterfs-cluster
          path: test1
          readOnly: false
      restartPolicy: Always
status: {}
